/* Aztec Conquest — engine.
 *
 * A feature-engine time model (ARCHITECTURE-PATTERNS §1): one scalar t drives
 * everything; every render is a pure function of state; every entity carries a
 * window; cards rewrite themselves for the current time.
 *
 * The canonical frame (SCOPE §5): t is a JULIAN fractional year. All Nahua
 * calendar equivalents shown anywhere are correlations and say so.
 *
 * The default view is the argument (SCOPE §1): the map draws ALLEGIANCE per
 * altepetl per day, from the state series generated by the research models.
 * If a first glance shows two colours, the model has already lied.
 *
 * Data files are GENERATED by Research/modeling/emit.py — do not hand-edit.
 */
'use strict';

const D = window.DATA;
const $ = s => document.querySelector(s);
const svg = $('#map');
const SVGNS = 'http://www.w3.org/2000/svg';

// ------------------------------------------------------------------ state --
const T0 = D.meta.t0, T1 = D.meta.t1;
const [CAMP0, CAMP1] = D.meta.campaign;
const SPEEDS = D.meta.speeds;

const state = {
  t: 1519.0,                         // open on the eve of the war
  playing: false,
  speed: 2,
  view: 'meso',
  layers: {},
  selection: null,
};

const LAYERS = D.meta.layers;
LAYERS.forEach(l => { state.layers[l.id] = l.on !== false; });

// --------------------------------------------------- the Julian calendar --
// Mirrors Research/modeling/calendar.py (the conversions' home); this is the
// display half only. One day = 1/365-or-366 of the Julian year.
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
             'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function yearDays(y) { return y % 4 === 0 ? 366 : 365; }

function julianOfT(t) {
  let y = Math.floor(t);
  let doy = Math.round((t - y) * yearDays(y));
  doy = Math.max(0, Math.min(yearDays(y) - 1, doy));
  const L = [31, y % 4 === 0 ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  let m = 0;
  while (doy >= L[m]) { doy -= L[m]; m++; }
  return [y, m + 1, doy + 1];
}

const inCampaign = t => t >= CAMP0 && t <= CAMP1;

function fmtT(t) {
  const [y, m, d] = julianOfT(t);
  return inCampaign(t) ? `${d} ${MON[m - 1]} ${y}` : String(y);
}

/* Keyboard/button step: one day inside the campaign, one month outside. */
function stepOf(t) { return inCampaign(t) ? 1 / 365.25 : 1 / 12; }

// ----------------------------------------------- non-linear time scale --
/* The scrubber is PIECEWISE (SCOPE §2): the campaign carries 56% of the track.
 * xOf and tOf are exact inverses; the breakpoints are drawn on the track and
 * labelled, so nobody mistakes the scale for linear. */
const TS = D.meta.timescale;

function xOf(t) {
  let x = 0;
  for (const s of TS) {
    if (t >= s.to) { x += s.w; continue; }
    if (t <= s.from) return x;
    return x + s.w * (t - s.from) / (s.to - s.from);
  }
  return 1;
}

function tOf(x) {
  let acc = 0;
  for (const s of TS) {
    if (x >= acc + s.w) { acc += s.w; continue; }
    if (x <= acc) return s.from;
    return s.from + (s.to - s.from) * (x - acc) / s.w;
  }
  return T1;
}

// ------------------------------------------------------------- projection --
/* Fixed equirectangular fit of the current view extent, with the lon scale
 * corrected by cos(mid-lat) so Basin shapes are not stretched. Three nested
 * scales (SCOPE §2): Mesoamerica / Basin / Tenochtitlan. */
let PROJ = null;

function computeProj() {
  const v = D.meta.views[state.view];
  const r = svg.getBoundingClientRect();
  const W = r.width, H = r.height - 130;           // leave room for the timeline
  const kx = Math.cos((v.lat0 + v.lat1) / 2 * Math.PI / 180);
  const dLon = (v.lon1 - v.lon0) * kx, dLat = v.lat1 - v.lat0;
  const s = Math.min(W / dLon, H / dLat) * 0.94;
  PROJ = {v, kx, s,
          x0: (W - dLon * s) / 2 - v.lon0 * kx * s,
          y0: (H - dLat * s) / 2 + v.lat1 * s + 20};
}

function project(lon, lat) {
  return [PROJ.x0 + lon * PROJ.kx * PROJ.s, PROJ.y0 - lat * PROJ.s];
}

function onScreen(x, y, m = 40) {
  const r = svg.getBoundingClientRect();
  return x > -m && y > -m && x < r.width + m && y < r.height + m;
}

// -------------------------------------------------------------- time model --
function activeAt(e, t) {
  if (e.from != null && t < e.from) return false;
  if (e.to != null && t > e.to) return false;
  return true;
}

function fadeIn(t, from, span) {
  if (from == null || from <= T0) return 1;
  return Math.max(0, Math.min(1, (t - from) / (span || 0.05)));
}

function lastLE(S, t) {
  let v = null;
  for (const row of S || []) { if (row[0] <= t) v = row[1]; else break; }
  return v;
}

function eraAt(t) {
  return D.eras.find(e => t >= e.from && t < e.to) || D.eras[D.eras.length - 1];
}

/* THE canonical allegiance reader — every consumer goes through this
 * (ARCHITECTURE-PATTERNS §4: one function returns the state; nothing reads a
 * second copy). */
function allegianceAt(e, t) { return lastLE(e.allegiance, t); }

const ALTEPETL = D.entities.filter(e => e.layer === 'altepetl');
const WORKS = D.entities.filter(e => e.layer === 'works');
const BY_ID = {};
D.entities.forEach(e => { BY_ID[e.id] = e; });
const TENOCH = BY_ID['tenochtitlan'];
const TRACK_EVENTS = D.eventsFull.filter(e => e.track);

// ----------------------------------------------------------------- render --
function render() {
  while (svg.firstChild) svg.removeChild(svg.firstChild);
  computeProj();

  if (state.layers.water) drawWater();
  if (state.layers.tribute) drawTribute();
  if (state.layers.track) drawTrack();
  if (state.layers.works) drawWorksHit();
  if (state.layers.altepetl) drawAltepetl();
  if (state.layers.events) drawEvents();

  updateReadout();
  updateTimeline();
  updateChapters();
  updateLegend();
  updateForces();
  if (state.selection) openCard(state.selection);
}

// The 1519 lake system and the works — drawn always as the substrate; the
// geometry is a named reconstruction and its cards say so.
function drawWater() {
  const g = el('g', {'data-layer': 'water'});
  for (const f of D.geo.features) {
    if (f.kind !== 'lake') continue;
    g.appendChild(el('path', {d: pathOf(f.points, true),
      fill: 'rgba(90,140,190,.20)', stroke: 'rgba(120,170,215,.45)',
      'stroke-width': 1}));
  }
  // the island city footprint, on the water
  const fp = D.geo.features.find(f => f.id === 'city-footprint');
  if (fp && state.view !== 'meso') {
    g.appendChild(el('path', {d: pathOf(fp.points, true),
      fill: 'rgba(200,180,140,.16)', stroke: 'rgba(200,180,140,.5)',
      'stroke-width': 1}));
  }
  svg.appendChild(g);
}

const WORK_STYLE = {
  causeway: {stroke: '#cbb894', w: 2.2, dash: null},
  aqueduct: {stroke: '#7fb8d8', w: 1.6, dash: '5 3'},
  dike: {stroke: '#9a8f7a', w: 1.8, dash: '2 3'},
};

function drawWorksHit() {
  if (state.view === 'meso') return;               // sub-Basin detail
  const g = el('g', {'data-layer': 'works'});
  for (const f of D.geo.features) {
    const st = WORK_STYLE[f.kind];
    if (!st) continue;
    const attrs = {d: pathOf(f.points, false), fill: 'none', stroke: st.stroke,
                   'stroke-width': st.w, 'stroke-linecap': 'round', class: 'work'};
    if (st.dash) attrs['stroke-dasharray'] = st.dash;
    const p = el('path', attrs);
    const card = BY_ID[f.id];
    if (card) p.addEventListener('click', ev => { ev.stopPropagation(); select(card); });
    g.appendChild(p);
  }
  svg.appendChild(g);
}

// Tribute flows: arcs from every polity still inside the tribute system to
// Tenochtitlan. They thin out as the coalition grows — the map's argument in
// motion — and end with the system itself.
function drawTribute() {
  const [cx, cy] = project(TENOCH.lon, TENOCH.lat);
  const g = el('g', {'data-layer': 'tribute'});
  for (const e of ALTEPETL) {
    if (e.id === 'tenochtitlan') continue;
    const st = allegianceAt(e, state.t);
    if (st !== 'tributary') continue;
    const [x, y] = project(e.lon, e.lat);
    // arcs only from on-screen sources — at Basin/City scale the far provinces'
    // arcs would otherwise flood the view with lines that carry no local information
    if (!onScreen(x, y, 160)) continue;
    const mx = (x + cx) / 2 + (y - cy) * 0.12, my = (y + cy) / 2 - (x - cx) * 0.12;
    g.appendChild(el('path', {d: `M${x},${y} Q${mx},${my} ${cx},${cy}`,
      fill: 'none', stroke: 'rgba(201,111,74,.30)', 'stroke-width': 0.8}));
  }
  svg.appendChild(g);
}

// The campaign track: the Spanish-led column's dated itinerary, drawn as far
// as the timeline has reached.
function drawTrack() {
  const done = TRACK_EVENTS.filter(e => e.t <= state.t);
  if (done.length < 1) return;
  const g = el('g', {'data-layer': 'track'});
  let dPath = '';
  for (let i = 0; i < done.length; i++) {
    const [x, y] = project(done[i].lon, done[i].lat);
    dPath += (i ? ' L' : 'M') + x.toFixed(1) + ',' + y.toFixed(1);
  }
  g.appendChild(el('path', {d: dPath, fill: 'none', stroke: '#d9d2c2',
    'stroke-width': 1.6, 'stroke-dasharray': '6 4', opacity: 0.8}));
  const head = done[done.length - 1];
  const [hx, hy] = project(head.lon, head.lat);
  g.appendChild(el('circle', {cx: hx, cy: hy, r: 4.5, fill: '#d9d2c2',
    stroke: 'rgba(0,0,0,.6)', 'stroke-width': 1}));
  svg.appendChild(g);
}

const GROUP_R = {'Triple Alliance seat': 6, 'Rival empire': 5.5,
                 'Independent polity': 5, 'Tributary altepetl': 4,
                 'Spanish foundation': 4.5};

function drawAltepetl() {
  const g = el('g', {'data-layer': 'altepetl'});
  const labelBudget = state.view === 'meso' ? 5 : 4.4;
  for (const e of ALTEPETL) {
    if (!activeAt(e, state.t)) continue;
    const st = allegianceAt(e, state.t);
    if (!st) continue;
    const [x, y] = project(e.lon, e.lat);
    if (!onScreen(x, y)) continue;
    const a = fadeIn(state.t, e.from, 0.05);
    const r = GROUP_R[e.kind] || 4;
    const color = D.meta.stateColor[st] || '#888';
    const mk = el('g', {class: 'mk', opacity: a});
    mk.appendChild(el('circle', {cx: x, cy: y, r,
      fill: color, stroke: 'rgba(0,0,0,.55)', 'stroke-width': 1}));
    if (e.confidence === 'contested')
      mk.appendChild(el('circle', {cx: x, cy: y, r: r + 2.5, fill: 'none',
        stroke: color, 'stroke-width': 0.8, 'stroke-dasharray': '2 2', opacity: 0.7}));
    if (r >= labelBudget)
      mk.appendChild(el('text', {x: x + r + 3, y: y + 3.5, class: 'mklab'},
        e.name.split(' (')[0]));
    mk.addEventListener('click', ev => { ev.stopPropagation(); select(e); });
    g.appendChild(mk);
  }
  svg.appendChild(g);
}

const KIND_GLYPH = {battle: '#d9a441', massacre: '#c0392b', siege: '#e0a458',
                    political: '#5aa9e6', campaign: '#d9d2c2', epidemic: '#8e6fb8',
                    aftermath: '#8a8f98', religious: '#4a9a8f'};

function drawEvents() {
  const win = inCampaign(state.t) ? 0.055 : 0.45;
  const g = el('g', {'data-layer': 'events'});
  for (const ev of D.eventsFull) {
    const dt = state.t - ev.t;
    if (dt < -win * 0.3 || dt > win) continue;      // appear at the date, linger after
    const [x, y] = project(ev.lon, ev.lat);
    if (!onScreen(x, y)) continue;
    const a = 1 - Math.max(0, dt) / win;
    const c = KIND_GLYPH[ev.kind] || '#ccc';
    const mk = el('g', {class: 'mk evmk', opacity: 0.25 + 0.75 * a});
    mk.appendChild(el('rect', {x: x - 3.6, y: y - 3.6, width: 7.2, height: 7.2,
      transform: `rotate(45 ${x} ${y})`, fill: c, stroke: 'rgba(0,0,0,.6)',
      'stroke-width': 1}));
    mk.appendChild(el('text', {x: x + 8, y: y + 3.5, class: 'mklab evlab'}, ev.name));
    mk.addEventListener('click', evn => { evn.stopPropagation(); select(ev); });
    g.appendChild(mk);
  }
  svg.appendChild(g);
}

function pathOf(points, close) {
  let d = '';
  for (let i = 0; i < points.length; i++) {
    const [x, y] = project(points[i][0], points[i][1]);
    d += (i ? ' L' : 'M') + x.toFixed(1) + ',' + y.toFixed(1);
  }
  return close ? d + ' Z' : d;
}

function el(tag, attrs, text) {
  const n = document.createElementNS(SVGNS, tag);
  for (const k in attrs) n.setAttribute(k, attrs[k]);
  if (text != null) n.textContent = text;
  return n;
}

// ------------------------------------------------------------------ cards --
function eraTextFor(o, t) {
  if (!o.eras || !o.eras.length) return o.text || '';
  const m = o.eras.find(e => t >= e.from && t < e.to);
  return m ? m.text : (t < o.eras[0].from ? o.eras[0] : o.eras[o.eras.length - 1]).text;
}

function eraSpanFor(o, t) {
  if (!o.eras || !o.eras.length) return '';
  const m = o.eras.find(e => t >= e.from && t < e.to) || o.eras[o.eras.length - 1];
  return `Describing ${fmtT(m.from)} – ${fmtT(m.to)}`;
}

function select(o) { state.selection = o; openCard(o); }

const CONF_LABEL = {good: 'well attested', moderate: 'moderately attested',
                    contested: 'CONTESTED'};

function openCard(o) {
  const isEvent = o.precision !== undefined;
  $('#infoTag').textContent = isEvent ? `event · ${o.kind}` : (o.kind || o.layer || '');
  $('#infoName').textContent = o.name;

  let rows = (o.facts || []).map(([k, v]) =>
    `<div class="row"><b>${esc(k)}</b><span>${esc(v)}</span></div>`);
  if (!isEvent && o.allegiance) {
    const st = allegianceAt(o, state.t);
    if (st) rows.push(`<div class="row"><b>Standing now</b><span>` +
      `<i class="dot" style="background:${D.meta.stateColor[st]}"></i>` +
      `${esc(D.meta.stateLabel[st] || st)}</span></div>`);
  }
  if (o.confidence) rows.push(`<div class="row"><b>Confidence</b>` +
    `<span class="conf-${o.confidence}">${CONF_LABEL[o.confidence] || o.confidence}</span></div>`);
  $('#infoRows').innerHTML = rows.join('');

  let body = esc(isEvent ? (o.text || '') : eraTextFor(o, state.t));
  if (o.note) body += `<div class="note">${esc(o.note)}</div>`;
  if (o.accounts && o.accounts.length) {
    body += `<div class="tier">What the sources say</div>` + o.accounts.map(a =>
      `<div class="account"><div class="acc-src">${esc(a.source)}</div>` +
      `<div class="acc-claim">${esc(a.claim)}</div>` +
      `<div class="acc-note">${esc(a.note)}</div></div>`).join('');
  }
  $('#infoDesc').innerHTML = body;
  $('#infoSpan').textContent = isEvent ? '' : eraSpanFor(o, state.t);
  $('#infoCite').innerHTML = (o.sources || []).length
    ? 'Sources: ' + o.sources.map(esc).join(' · ') : '';
  $('#info').classList.remove('hidden');
}

// --------------------------------------------------------------- readout --
function updateReadout() {
  $('#tBig').textContent = fmtT(state.t);
  $('#tCal').textContent = inCampaign(state.t) ? 'Julian calendar · day scale' : '';
  const era = eraAt(state.t);
  $('#eraName').textContent = era ? era.name : '';
  // live allegiance tally — reads the same series as the map (one source of truth)
  const counts = {};
  for (const e of ALTEPETL) {
    const st = allegianceAt(e, state.t);
    if (st) counts[st] = (counts[st] || 0) + 1;
  }
  const top = Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 3);
  $('#statsBlock').innerHTML = top.map(([st, n]) =>
    `<div class="statline"><b>${esc(D.meta.stateLabel[st] || st)}</b>${n}</div>`).join('');
}

function updateLegend() {
  const counts = {};
  for (const e of ALTEPETL) {
    const st = allegianceAt(e, state.t);
    if (st) counts[st] = (counts[st] || 0) + 1;
  }
  const order = Object.keys(D.meta.stateColor);
  $('#legendBody').innerHTML = order.filter(st => counts[st]).map(st =>
    `<div class="lg"><i class="dot" style="background:${D.meta.stateColor[st]}"></i>` +
    `<span>${esc(D.meta.stateLabel[st] || st)}</span><b>${counts[st]}</b></div>`).join('');
}

function updateForces() {
  const rows = D.forces.filter(r => r[0] <= state.t);
  const panel = $('#forcesPanel');
  if (!rows.length) { panel.classList.add('hidden'); return; }
  const [, label, bands] = rows[rows.length - 1];
  panel.classList.remove('hidden');
  const COL = {'Spanish': '#6b7fa8', 'Tlaxcalteca and Nahua allies': '#3f8f6b',
               'Mexica defenders': '#a83232'};
  $('#forcesBody').innerHTML = `<div class="fphase">${esc(label)}</div>` +
    Object.entries(bands).filter(([, b]) => b[1] > 0).map(([c, b]) =>
      `<div class="lg"><i class="dot" style="background:${COL[c]}"></i>` +
      `<span>${esc(c.replace(' and Nahua allies', ' + Nahua allies'))}</span>` +
      `<b>${b[0].toLocaleString()}–${b[1].toLocaleString()}</b></div>`).join('') +
    `<div class="fnote">ranges, not numbers — the sources are parties to the count</div>`;
}

// -------------------------------------------------------------- timeline --
function buildTimeline() {
  const band = $('#eraBand'), labs = $('#eraLabels'), dots = $('#eventDots'),
        ticks = $('#tickRow');
  band.innerHTML = labs.innerHTML = dots.innerHTML = ticks.innerHTML = '';
  D.eras.forEach((e, i) => {
    const d = document.createElement('div');
    d.style.left = xOf(e.from) * 100 + '%';
    d.style.width = (xOf(e.to) - xOf(e.from)) * 100 + '%';
    d.style.background = i % 2 ? 'rgba(224,164,88,.20)' : 'rgba(90,169,230,.18)';
    d.title = e.name;
    d.onclick = () => seek(e.from + 1e-4);
    band.appendChild(d);
    if (xOf(e.to) - xOf(e.from) > 0.055) {
      const s = document.createElement('span');
      s.style.left = (xOf(e.from) + xOf(e.to)) / 2 * 100 + '%';
      s.textContent = e.name;
      labs.appendChild(s);
    }
  });
  (D.events || []).forEach(ev => {
    const d = document.createElement('div');
    d.style.left = xOf(ev.t) * 100 + '%';
    d.title = `${fmtT(ev.t)} — ${ev.name}`;
    d.onclick = e => {
      e.stopPropagation(); seek(ev.t);
      const full = D.eventsFull.find(f => f.id === ev.id);
      if (full) select(full);
    };
    dots.appendChild(d);
  });
  // the non-linear scale, made visible: breakpoints + segment labels
  TS.forEach((s, i) => {
    if (i) {
      const b = document.createElement('div');
      b.className = 'tsbreak';
      b.style.left = xOf(s.from) * 100 + '%';
      ticks.appendChild(b);
    }
    const lab = document.createElement('span');
    lab.className = 'tslab';
    lab.style.left = (xOf(s.from) + xOf(s.to)) / 2 * 100 + '%';
    lab.textContent = i === 1 ? 'day scale — the war, 1519–1521' :
      `${Math.round(s.from)}–${Math.round(s.to)}`;
    ticks.appendChild(lab);
  });
}

function updateTimeline() {
  const f = xOf(state.t) * 100;
  $('#trackFill').style.width = f + '%';
  $('#thumb').style.left = f + '%';
  const win = stepOf(state.t) * 2;
  const near = (D.events || []).filter(e => Math.abs(e.t - state.t) <= win);
  $('#eventReadout').textContent = near.length ? near[0].name : '';
}

function buildChapters() {
  $('#chapterList').innerHTML = D.eras
    .map((e, i) => `<div data-i="${i}">${esc(e.name)}</div>`).join('');
  $('#chapterList').querySelectorAll('div').forEach(d =>
    d.onclick = () => seek(D.eras[+d.dataset.i].from + 1e-4));
}

function updateChapters() {
  const era = eraAt(state.t);
  $('#chapterList').querySelectorAll('div').forEach((d, i) =>
    d.classList.toggle('on', D.eras[i] === era));
}

// -------------------------------------------------------------- playback --
let raf = null, last = 0;

function tick(ts) {
  if (!state.playing) return;
  if (last) state.t = Math.min(T1, state.t + SPEEDS[state.speed] * (ts - last) / 1000);
  last = ts;
  if (state.t >= T1) pause();
  render(); syncHash();
  raf = requestAnimationFrame(tick);
}

function play()  { state.playing = true; last = 0; $('#playIcon').textContent = '❚❚';
                   raf = requestAnimationFrame(tick); }
function pause() { state.playing = false; $('#playIcon').textContent = '▶';
                   if (raf) cancelAnimationFrame(raf); }

function seek(t) {
  state.t = Math.max(T0, Math.min(T1, t));
  render(); syncHash();
}

function jumpEvent(dir) {
  const es = (D.events || []).map(e => e.t).sort((a, b) => a - b);
  const next = dir > 0 ? es.find(t => t > state.t + 1e-6)
                       : [...es].reverse().find(t => t < state.t - 1e-6);
  if (next != null) seek(next);
}

function setView(v) {
  state.view = v;
  $('#viewBtns').querySelectorAll('button').forEach(b =>
    b.classList.toggle('on', b.dataset.v === v));
  render(); syncHash();
}

// ------------------------------------------------------------------ hash --
function syncHash() {
  history.replaceState(null, '', `#t=${state.t.toFixed(4)}&v=${state.view}`);
}
function readHash() {
  const m = /[#&]t=(-?\d+(?:\.\d+)?)/.exec(location.hash);
  if (m) state.t = Math.max(T0, Math.min(T1, parseFloat(m[1])));
  const v = /[#&]v=(\w+)/.exec(location.hash);
  if (v && D.meta.views[v[1]]) state.view = v[1];
}

// ------------------------------------------------------------------ about --
function buildAbout() {
  const a = D.meta.about;
  $('#aboutBody').innerHTML =
    `<p><b>What this is.</b> ${esc(a.what)}</p>` +
    `<p><b>On the name.</b> ${esc(a.naming)}</p>` +
    `<h3>What this model does not know</h3>` +
    a.notKnow.map(x => `<p>· ${esc(x)}</p>`).join('') +
    `<h3>Sources</h3>` + a.sources.map(x => `<p>· ${esc(x)}</p>`).join('') +
    `<h3>Method</h3><p>Every layer is generated from cited research models with selftests ` +
    `(Research/modeling/); two read-only audits gate every build: the card audit (era tiling, ` +
    `contested claims must carry their accounts, anachronisms) and the archaeological witness ` +
    `audit (drawn geography vs the Templo Mayor anchor table and literature bands). ` +
    `Data version: <span id="dvStamp">${esc(String(D.meta.dataVersion || 'dev'))}</span>.</p>`;
}

// ------------------------------------------------------------------ wire --
function buildToggles() {
  $('#layerToggles').innerHTML = LAYERS.map(l =>
    `<label class="tog"><span>${esc(l.label)}</span>` +
    `<input type="checkbox" data-id="${l.id}"${state.layers[l.id] ? ' checked' : ''}><i></i></label>`
  ).join('');
  $('#layerToggles').querySelectorAll('input').forEach(i =>
    i.onchange = () => { state.layers[i.dataset.id] = i.checked; render(); });
}

function buildViews() {
  $('#viewBtns').innerHTML = Object.entries(D.meta.views).map(([id, v]) =>
    `<button data-v="${id}"${id === state.view ? ' class="on"' : ''}>${esc(v.label)}</button>`
  ).join('');
  $('#viewBtns').querySelectorAll('button').forEach(b =>
    b.onclick = () => setView(b.dataset.v));
}

function wire() {
  $('#playBtn').onclick  = () => state.playing ? pause() : play();
  $('#stepBack').onclick = () => seek(state.t - stepOf(state.t));
  $('#stepFwd').onclick  = () => seek(state.t + stepOf(state.t));
  $('#prevEvt').onclick  = () => jumpEvent(-1);
  $('#nextEvt').onclick  = () => jumpEvent(1);
  $('#speed').oninput = e => {
    state.speed = +e.target.value;
    $('#speedVal').textContent = SPEEDS[state.speed] + ' yr/s';
  };
  $('#speed').oninput({target: $('#speed')});

  const track = $('#track');
  const at = e => tOf((e.clientX - track.getBoundingClientRect().left) / track.clientWidth);
  let dragging = false;
  track.onpointerdown = e => { dragging = true; track.setPointerCapture(e.pointerId);
                               pause(); seek(at(e)); };
  track.onpointermove = e => { if (dragging) seek(at(e)); };
  track.onpointerup   = () => { dragging = false; };

  $('#infoClose').onclick  = () => { state.selection = null; $('#info').classList.add('hidden'); };
  $('#aboutBtn').onclick   = () => $('#about').classList.remove('hidden');
  $('#aboutClose').onclick = () => $('#about').classList.add('hidden');
  $('#chaptersChev').onclick = () => {
    const l = $('#chapterList');
    l.style.display = l.style.display === 'none' ? '' : 'none';
  };
  svg.addEventListener('click', () => {
    state.selection = null; $('#info').classList.add('hidden');
  });

  addEventListener('keydown', e => {
    if (e.target.tagName === 'INPUT') return;
    if (e.code === 'Space') { e.preventDefault(); state.playing ? pause() : play(); }
    else if (e.key === 'ArrowLeft')  e.shiftKey ? jumpEvent(-1) : seek(state.t - stepOf(state.t));
    else if (e.key === 'ArrowRight') e.shiftKey ? jumpEvent(1)  : seek(state.t + stepOf(state.t));
    else if (e.key === 'Escape') { state.selection = null; $('#info').classList.add('hidden'); }
  });

  addEventListener('resize', render);
  addEventListener('hashchange', () => { readHash(); render(); });
}

const esc = s => String(s == null ? '' : s)
  .replace(/[&<>"]/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;'}[c]));

// ------------------------------------------------------------------ boot --
readHash();
buildTimeline();
buildChapters();
buildToggles();
buildViews();
buildAbout();
wire();
render();

// Console handle, so verification is scriptable:
//   APP.seek(1521.5); APP.state; APP.allegianceAt(APP.BY_ID.tlaxcala, 1521)
window.APP = {state, seek, play, pause, render, project, activeAt, lastLE,
              allegianceAt, xOf, tOf, fmtT, BY_ID, LAYERS, setView};
